### ISSUE TITLE
1.19.2 Sapling Crashes Server

### ISSUE THREAD

**Issue by Looodon** [skyjay1/GreekFantasy#104]
Hey, I've been using the mod for days without issues. The only issue I ran into is when I plant the saplings on the floor and wait for them to grow then the world crashes when they are supposed to grow. When I use bone meal on them they disappear.

**Forge**: 43.1.1
**Minecraft:** 1.19.2

**Mods:**
_vanilla, kiwi , companion , greekfantasy, jei , attributefix , goblintraders , gravestone , collective, levelhearts , configurableextramobdrops, journeymap , configured , dungeoncrawl, buildersaddition , guardvillagers , friendlygriefing , inventoryprofilesnext , hunterillager, additionalstructures, puzzleslib , blueprint , savage_and_ravage , fallingtree, enchantwithmob, cloth_config , sound_physics_remastered , forge, passthroughsigns, appleskin, t_and_t, leashed, friendsandfoes , xpbook, tenshilib , badmobs , aiimprovements, improvedmobs , swingthroughgrass , publicguiannouncement , torohealth, rubidium , modnametooltip , rangedwirelessredstone , nounusedchunks , entity_texture_features , toolswap, dogslie, notenoughanimations , oculus , sodiumextra , pinghud , inventoryhud, moreoverlays , betterf3, bettermodsbutton_ 

**Crash:**
> java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(net.minecraft.world.level.WorldGenLevel, net.minecraft.world.level.chunk.ChunkGenerator, net.minecraft.util.RandomSource, net.minecraft.core.BlockPos)" because "$$6" is null
	at net.minecraft.world.level.block.grower.AbstractTreeGrower.m_213817_(AbstractTreeGrower.java:31) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading}
	at net.minecraft.world.level.block.SaplingBlock.m_222000_(SaplingBlock.java:46) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.SaplingBlock.m_213898_(SaplingBlock.java:36) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:698) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:360) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by skyjay1** [comment]
All Saplings cause a crash? Or only from this mod? All of the saplings from this mod?

**Comment by Looodon** [comment]
It's only from the Greek Fantasy mod that the saplings disappear and cause a crash

**Comment by Looodon** [comment]
I did a small test. I took out all mods except Greek Fantasy and tried to bone meal all saplings.
- Overworld: Pomegrante Sapling explodes, Olive Sapling Disappear, Golden Sapling Disappear
- Nether: Pomegrante Sapling Disappears, can't plant the others

When left to grow on their own without bone meal the game crashes I assume when the game registers that the sapling needs to go to the next stage.

**Comment by skyjay1** [comment]
This will be included in the next 1.18 and 1.19 releases
