### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by HavokHurricane** [skyjay1/GreekFantasy#114]
Description: Exception ticking world

java.lang.IllegalArgumentException: Unsupported mob type for FollowWaterMobGoal
	at greekfantasy.entity.ai.FollowWaterMobGoal.<init>(FollowWaterMobGoal.java:34) ~[greekfantasy-19.2.1.jar%23114!/:19.2.1] {re:classloading}
	at greekfantasy.GFEvents$ForgeHandler$2.<init>(GFEvents.java:555) ~[greekfantasy-19.2.1.jar%23114!/:19.2.1] {re:classloading}
	at greekfantasy.GFEvents$ForgeHandler.onEntityJoinWorld(GFEvents.java:555) ~[greekfantasy-19.2.1.jar%23114!/:19.2.1] {re:classloading}
	at greekfantasy.__ForgeHandler_onEntityJoinWorld_EntityJoinLevelEvent.invoke(.dynamic) ~[greekfantasy-19.2.1.jar%23114!/:19.2.1] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:79) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157592_(PersistentEntitySectionManager.java:260) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:classloading}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157582_(PersistentEntitySectionManager.java:259) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157506_(PersistentEntitySectionManager.java:269) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:335) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at greekfantasy.entity.ai.FollowWaterMobGoal.<init>(FollowWaterMobGoal.java:34) ~[greekfantasy-19.2.1.jar%23114!/:19.2.1] {re:classloading}
	at greekfantasy.GFEvents$ForgeHandler$2.<init>(GFEvents.java:555) ~[greekfantasy-19.2.1.jar%23114!/:19.2.1] {re:classloading}
	at greekfantasy.GFEvents$ForgeHandler.onEntityJoinWorld(GFEvents.java:555) ~[greekfantasy-19.2.1.jar%23114!/:19.2.1] {re:classloading}
	at greekfantasy.__ForgeHandler_onEntityJoinWorld_EntityJoinLevelEvent.invoke(.dynamic) ~[greekfantasy-19.2.1.jar%23114!/:19.2.1] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:79) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157592_(PersistentEntitySectionManager.java:260) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:classloading}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157582_(PersistentEntitySectionManager.java:259) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157506_(PersistentEntitySectionManager.java:269) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:335) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['HavokHurcane'/879, l='ServerLevel[world]', x=-4514.45, y=54.07, z=63.65]]
	Chunk stats: 930
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (0,73,0), Section: (at 0,9,0 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 21452 game time, 7539 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 145418 (now: false), thunder time: 52093 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

server-1.19.2-20220805.130853-srg.jar  
		tenshilib-1.19-1.6.10-forge.jar   
		TerraBlender-forge-1.19.2-2.0.1.127.jar  
		greekfantasy-19.2.1.jar  
		BiomesOPlenty-1.19.2-17.1.1.152.jar  
		the-conjurer-1.19.2-1.1.4.jar  
		justmobheads_1.19.2-6.0.jar   
		goblintraders-1.8.0-1.19.2.jar   
		rubidium-0.6.2.jar  
		curios-forge-1.19.2-5.1.1.0.jar 
		Patchouli-1.19.2-76.jar  
		collective-1.19.2-4.69.jar  
		citadel-1.12.12-1.19.jar  
		alexsmobs-1.20.1.jar   
		tombstone-8.1.6-1.19.2.jar    
		betteranimalsplus-1.19-11.0.7-forge.jar  
		Guide-API-VP-1.19.2-2.2.4.jar 
		architectury-6.2.46-forge.jar 
		Terralith_v2.3.4.jar  
		PuzzlesLib-v4.3.8-1.19.2-Forge.jar 
		Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.11.jar 
		Corail-Backpack-1.19.2-155.jar   
		cloth-config-8.2.88-forge.jar 
		forge-1.19.2-43.1.32-universal.jar   
		commonality-1.19.2-4.2.0.jar 
		apexcore-1.19.2-7.3.0.jar  
		fantasyfurniture-1.19.2-6.5.0.jar  
		improvedmobs-1.19-1.10.15-forge.jar   
		twilightforest-1.19-4.2.1421-universal.jar 
		geckolib-forge-1.19-3.1.21.jar  
		ars_nouveau-1.19.2-3.4.0.jar 
		EnchantingInfuser-v4.2.1-1.19.2-Forge.jar        
		DungeonsArise-1.19-2.1.51-beta.jar

I was in the aviary dungeon for Dungeons arise. I reset the world, as I am just testing mods right now to create a new server, and this bug is recreatable each time. only in that dungeon. I had no issues around any other mob spawners anywhere else.

I love your mod a lot as well as the rest on this list so far, so I would really like to be able to use them. 

Thank you.

**Comment by skyjay1** [comment]
The most likely reason for this crash is that another mod is changing the Guardian pathfinding to something other than `WaterBoundPathNavigation`. 

I don't think the goal that I'm using was working anyway, I'll remove it in the next release and that should solve this problem.
