### ISSUE TITLE
1.19.2 Crash

### ISSUE THREAD

**Issue by norfaremc** [skyjay1/GreekFantasy#140]
Random crash on our server, it mentions greek fantasy in the logs. The player that caused the crash said he was above an arachne dungeon, pouring water in to break the cobwebs. Any ideas?

This is the message that kept popping up in our debug log:
[greekfantasy/]: dot=0.6026841597861337

Time: 2023-07-05 21:47:40
Description: Exception in server tick loop

java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?] {}
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?] {}
	at com.google.common.collect.Iterators$1.next(Iterators.java:146) ~[guava-31.0.1-jre.jar%2372!/:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157543_(PersistentEntitySectionManager.java:175) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177) ~[?:?] {}
	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:183) ~[?:?] {}
	at java.util.Spliterators$LongIteratorSpliterator.forEachRemaining(Spliterators.java:2046) ~[?:?] {}
	at java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:775) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157527_(PersistentEntitySectionManager.java:160) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157524_(PersistentEntitySectionManager.java:146) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.m_143075_(ChunkMap.java:1256) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.dynamic.ChunkMapMixin,pl:mixin:APP:servercore.common.mixins.json:features.misc.ChunkMapMixin,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ChunkManagerMixin,pl:mixin:APP:smallships-common-soft.mixins.json:leashing.ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkHolder.m_142992_(ChunkHolder.java:347) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.broadcast.ChunkHolderMixin,pl:mixin:APP:chunkpregen.mixins.json:common.chunk.ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkHolder.m_143003_(ChunkHolder.java:417) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.broadcast.ChunkHolderMixin,pl:mixin:APP:chunkpregen.mixins.json:common.chunk.ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.server.level.DistanceManager.m_183906_(DistanceManager.java:124) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,re:classloading,pl:mixin:APP:chunkpregen.mixins.json:common.storage.TicketManagerMixin,pl:mixin:A}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraft.server.level.DistanceManager.m_140805_(DistanceManager.java:123) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,re:classloading,pl:mixin:APP:chunkpregen.mixins.json:common.storage.TicketManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8489_(ServerChunkCache.java:271) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.broadcast.ServerChunkCacheMixin,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.cache.ServerChunkCacheMixin,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.random.ServerChunkCacheMixin,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ServerChunkProviderMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:539) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:267) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.broadcast.ServerChunkCacheMixin,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.cache.ServerChunkCacheMixin,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.random.ServerChunkCacheMixin,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ServerChunkProviderMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:751) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23583!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

**Comment by skyjay1** [comment]
Not a clue. I see so many mixins in the log that I do not know which one caused the problem. Does the crash occur without chunkpregen mod?

**Comment by norfaremc** [comment]
Crash occurs without pregen mod. At this point, this is ALL my logs consist of, CONSTANTLY. I don't know what this is and it keeps timing out our world:
[18Jul2023 20:13:47.929] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9103223085403442, 0.0, 0.4139001667499542)
[18Jul2023 20:13:47.929] [Server thread/DEBUG] [greekfantasy/]: dot=0.891536971975686
[18Jul2023 20:13:47.967] [Server thread/INFO] [APTweaks(Core)/]: [APTweaks:Core] ↓ Server load changed from NORMAL (avg. 43.8510856628418) to VERY_LOW (avg. 15.577398300170898)
[18Jul2023 20:13:47.978] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9996293187141418, 0.0, -0.027128957211971283)
[18Jul2023 20:13:47.978] [Server thread/DEBUG] [greekfantasy/]: dot=-0.6450761820965907
[18Jul2023 20:13:48.027] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9441002607345581, 0.0, 0.3296584486961365)
[18Jul2023 20:13:48.027] [Server thread/DEBUG] [greekfantasy/]: dot=0.8467970705236709
[18Jul2023 20:13:48.078] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9989719390869141, 0.0, 0.04533276706933975)
[18Jul2023 20:13:48.078] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5880489542655623
[18Jul2023 20:13:48.127] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.961649477481842, 0.0, 0.2742813229560852)
[18Jul2023 20:13:48.127] [Server thread/DEBUG] [greekfantasy/]: dot=0.8144815853067442
[18Jul2023 20:13:48.178] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9957849979400635, 0.0, 0.09171801805496216)
[18Jul2023 20:13:48.178] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5498174860595881
[18Jul2023 20:13:48.227] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9711848497390747, 0.0, 0.23832738399505615)
[18Jul2023 20:13:48.227] [Server thread/DEBUG] [greekfantasy/]: dot=0.7923406080978879
[18Jul2023 20:13:48.281] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9926196932792664, 0.0, 0.12126876413822174)
[18Jul2023 20:13:48.281] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5247529252949885
[18Jul2023 20:13:48.329] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9765764474868774, 0.0, 0.21517062187194824)
[18Jul2023 20:13:48.329] [Server thread/DEBUG] [greekfantasy/]: dot=0.777612351205363
[18Jul2023 20:13:48.428] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9103619456291199, 0.0, 0.41381287574768066)
[18Jul2023 20:13:48.428] [Server thread/DEBUG] [greekfantasy/]: dot=-0.24483975360419663
[18Jul2023 20:13:48.478] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.999631941318512, 0.0, -0.027128957211971283)
[18Jul2023 20:13:48.478] [Server thread/DEBUG] [greekfantasy/]: dot=0.6026841597861337
[18Jul2023 20:13:48.527] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9441318511962891, 0.0, 0.32956793904304504)
[18Jul2023 20:13:48.527] [Server thread/DEBUG] [greekfantasy/]: dot=-0.3317395106069476
[18Jul2023 20:13:48.577] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9989675879478455, 0.0, 0.04542854055762291)
[18Jul2023 20:13:48.577] [Server thread/DEBUG] [greekfantasy/]: dot=0.6589613111817942
[18Jul2023 20:13:48.627] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9616758227348328, 0.0, 0.2741891145706177)
[18Jul2023 20:13:48.627] [Server thread/DEBUG] [greekfantasy/]: dot=-0.3859583573652259
[18Jul2023 20:13:48.677] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9957762360572815, 0.0, 0.09181348979473114)
[18Jul2023 20:13:48.677] [Server thread/DEBUG] [greekfantasy/]: dot=0.6932117826967126
[18Jul2023 20:13:48.727] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9712077379226685, 0.0, 0.2382342666387558)
[18Jul2023 20:13:48.727] [Server thread/DEBUG] [greekfantasy/]: dot=-0.4200001428753257
[18Jul2023 20:13:48.779] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9926080703735352, 0.0, 0.12136393040418625)
[18Jul2023 20:13:48.779] [Server thread/DEBUG] [greekfantasy/]: dot=0.7143233181817186
[18Jul2023 20:13:48.827] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9765970706939697, 0.0, 0.2150769829750061)
[18Jul2023 20:13:48.827] [Server thread/DEBUG] [greekfantasy/]: dot=-0.441457301345217
[18Jul2023 20:13:48.927] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9103223085403442, 0.0, 0.4139001667499542)
[18Jul2023 20:13:48.927] [Server thread/DEBUG] [greekfantasy/]: dot=0.891536971975686
[18Jul2023 20:13:48.981] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9996293187141418, 0.0, -0.027128957211971283)
[18Jul2023 20:13:48.981] [Server thread/DEBUG] [greekfantasy/]: dot=-0.6450761820965907
[18Jul2023 20:13:49.026] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9441002607345581, 0.0, 0.3296584486961365)
[18Jul2023 20:13:49.026] [Server thread/DEBUG] [greekfantasy/]: dot=0.8467970705236709
[18Jul2023 20:13:49.081] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9989719390869141, 0.0, 0.04533276706933975)
[18Jul2023 20:13:49.081] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5880489542655623
[18Jul2023 20:13:49.127] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.961649477481842, 0.0, 0.2742813229560852)
[18Jul2023 20:13:49.127] [Server thread/DEBUG] [greekfantasy/]: dot=0.8144815853067442
[18Jul2023 20:13:49.178] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9957849979400635, 0.0, 0.09171801805496216)
[18Jul2023 20:13:49.178] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5498174860595881
[18Jul2023 20:13:49.217] [Server thread/INFO] [APTweaks(Core)/]: [APTweaks:Core] ↓ Level load for minecraft:overworld changed from MEDIUM (avg. 44.694390240000004) to VERY_LOW (avg. 10.37010268)
[18Jul2023 20:13:49.228] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9711848497390747, 0.0, 0.23832738399505615)
[18Jul2023 20:13:49.228] [Server thread/DEBUG] [greekfantasy/]: dot=0.7923406080978879
[18Jul2023 20:13:49.278] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9926196932792664, 0.0, 0.12126876413822174)
[18Jul2023 20:13:49.278] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5247529252949885
[18Jul2023 20:13:49.328] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9765764474868774, 0.0, 0.21517062187194824)
[18Jul2023 20:13:49.328] [Server thread/DEBUG] [greekfantasy/]: dot=0.777612351205363
[18Jul2023 20:13:49.424] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9103619456291199, 0.0, 0.41381287574768066)
[18Jul2023 20:13:49.424] [Server thread/DEBUG] [greekfantasy/]: dot=-0.24483975360419663
[18Jul2023 20:13:49.480] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.999631941318512, 0.0, -0.027128957211971283)
[18Jul2023 20:13:49.480] [Server thread/DEBUG] [greekfantasy/]: dot=0.6026841597861337
[18Jul2023 20:13:49.526] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9441318511962891, 0.0, 0.32956793904304504)
[18Jul2023 20:13:49.526] [Server thread/DEBUG] [greekfantasy/]: dot=-0.3317395106069476
[18Jul2023 20:13:49.578] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9989675879478455, 0.0, 0.04542854055762291)
[18Jul2023 20:13:49.578] [Server thread/DEBUG] [greekfantasy/]: dot=0.6589613111817942
[18Jul2023 20:13:49.625] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9616758227348328, 0.0, 0.2741891145706177)
[18Jul2023 20:13:49.625] [Server thread/DEBUG] [greekfantasy/]: dot=-0.3859583573652259
[18Jul2023 20:13:49.676] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9957762360572815, 0.0, 0.09181348979473114)
[18Jul2023 20:13:49.676] [Server thread/DEBUG] [greekfantasy/]: dot=0.6932117826967126
[18Jul2023 20:13:49.726] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9712077379226685, 0.0, 0.2382342666387558)
[18Jul2023 20:13:49.726] [Server thread/DEBUG] [greekfantasy/]: dot=-0.4200001428753257
[18Jul2023 20:13:49.777] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9926080703735352, 0.0, 0.12136393040418625)
[18Jul2023 20:13:49.777] [Server thread/DEBUG] [greekfantasy/]: dot=0.7143233181817186
[18Jul2023 20:13:49.825] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9765970706939697, 0.0, 0.2150769829750061)
[18Jul2023 20:13:49.825] [Server thread/DEBUG] [greekfantasy/]: dot=-0.441457301345217
[18Jul2023 20:13:49.925] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9103223085403442, 0.0, 0.4139001667499542)
[18Jul2023 20:13:49.925] [Server thread/DEBUG] [greekfantasy/]: dot=0.891536971975686
[18Jul2023 20:13:49.974] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9996293187141418, 0.0, -0.027128957211971283)
[18Jul2023 20:13:49.974] [Server thread/DEBUG] [greekfantasy/]: dot=-0.6450761820965907
[18Jul2023 20:13:50.024] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9441002607345581, 0.0, 0.3296584486961365)
[18Jul2023 20:13:50.024] [Server thread/DEBUG] [greekfantasy/]: dot=0.8467970705236709
[18Jul2023 20:13:50.080] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9989719390869141, 0.0, 0.04533276706933975)
[18Jul2023 20:13:50.080] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5880489542655623
[18Jul2023 20:13:50.127] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.961649477481842, 0.0, 0.2742813229560852)
[18Jul2023 20:13:50.127] [Server thread/DEBUG] [greekfantasy/]: dot=0.8144815853067442
[18Jul2023 20:13:50.177] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9957849979400635, 0.0, 0.09171801805496216)
[18Jul2023 20:13:50.177] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5498174860595881
[18Jul2023 20:13:50.227] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9711848497390747, 0.0, 0.23832738399505615)
[18Jul2023 20:13:50.227] [Server thread/DEBUG] [greekfantasy/]: dot=0.7923406080978879
[18Jul2023 20:13:50.278] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9926196932792664, 0.0, 0.12126876413822174)
[18Jul2023 20:13:50.278] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5247529252949885
[18Jul2023 20:13:50.327] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9765764474868774, 0.0, 0.21517062187194824)
[18Jul2023 20:13:50.327] [Server thread/DEBUG] [greekfantasy/]: dot=0.777612351205363
[18Jul2023 20:13:50.428] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9103619456291199, 0.0, 0.41381287574768066)
[18Jul2023 20:13:50.428] [Server thread/DEBUG] [greekfantasy/]: dot=-0.24483975360419663
[18Jul2023 20:13:50.478] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.999631941318512, 0.0, -0.027128957211971283)
[18Jul2023 20:13:50.478] [Server thread/DEBUG] [greekfantasy/]: dot=0.6026841597861337
[18Jul2023 20:13:50.528] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9441318511962891, 0.0, 0.32956793904304504)
[18Jul2023 20:13:50.528] [Server thread/DEBUG] [greekfantasy/]: dot=-0.3317395106069476
[18Jul2023 20:13:50.582] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9989675879478455, 0.0, 0.04542854055762291)
[18Jul2023 20:13:50.582] [Server thread/DEBUG] [greekfantasy/]: dot=0.6589613111817942
[18Jul2023 20:13:50.627] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9616758227348328, 0.0, 0.2741891145706177)
[18Jul2023 20:13:50.627] [Server thread/DEBUG] [greekfantasy/]: dot=-0.3859583573652259
[18Jul2023 20:13:50.678] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9957762360572815, 0.0, 0.09181348979473114)
[18Jul2023 20:13:50.678] [Server thread/DEBUG] [greekfantasy/]: dot=0.6932117826967126
[18Jul2023 20:13:50.727] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9712077379226685, 0.0, 0.2382342666387558)
[18Jul2023 20:13:50.727] [Server thread/DEBUG] [greekfantasy/]: dot=-0.4200001428753257
[18Jul2023 20:13:50.777] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9926080703735352, 0.0, 0.12136393040418625)
[18Jul2023 20:13:50.777] [Server thread/DEBUG] [greekfantasy/]: dot=0.7143233181817186
[18Jul2023 20:13:50.827] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9765970706939697, 0.0, 0.2150769829750061)
[18Jul2023 20:13:50.827] [Server thread/DEBUG] [greekfantasy/]: dot=-0.441457301345217
[18Jul2023 20:13:50.927] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9103223085403442, 0.0, 0.4139001667499542)
[18Jul2023 20:13:50.927] [Server thread/DEBUG] [greekfantasy/]: dot=0.891536971975686
[18Jul2023 20:13:50.978] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9996293187141418, 0.0, -0.027128957211971283)
[18Jul2023 20:13:50.978] [Server thread/DEBUG] [greekfantasy/]: dot=-0.6450761820965907
[18Jul2023 20:13:51.029] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9441002607345581, 0.0, 0.3296584486961365)
[18Jul2023 20:13:51.029] [Server thread/DEBUG] [greekfantasy/]: dot=0.8467970705236709
[18Jul2023 20:13:51.081] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9989719390869141, 0.0, 0.04533276706933975)
[18Jul2023 20:13:51.081] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5880489542655623
[18Jul2023 20:13:51.127] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.961649477481842, 0.0, 0.2742813229560852)
[18Jul2023 20:13:51.127] [Server thread/DEBUG] [greekfantasy/]: dot=0.8144815853067442
[18Jul2023 20:13:51.178] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9957849979400635, 0.0, 0.09171801805496216)
[18Jul2023 20:13:51.178] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5498174860595881
[18Jul2023 20:13:51.227] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9711848497390747, 0.0, 0.23832738399505615)
[18Jul2023 20:13:51.227] [Server thread/DEBUG] [greekfantasy/]: dot=0.7923406080978879
[18Jul2023 20:13:51.278] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9926196932792664, 0.0, 0.12126876413822174)
[18Jul2023 20:13:51.278] [Server thread/DEBUG] [greekfantasy/]: dot=-0.5247529252949885
[18Jul2023 20:13:51.327] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.9765764474868774, 0.0, 0.21517062187194824)
[18Jul2023 20:13:51.327] [Server thread/DEBUG] [greekfantasy/]: dot=0.777612351205363
[18Jul2023 20:13:51.427] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(0.9103619456291199, 0.0, 0.41381287574768066)
[18Jul2023 20:13:51.427] [Server thread/DEBUG] [greekfantasy/]: dot=-0.24483975360419663
[18Jul2023 20:13:51.477] [Server thread/DEBUG] [greekfantasy/]: 
first=(-0.6241106986999512, 0.0, 0.7813359498977661)
second=(-0.999631941318512, 0.0, -0.027128957211971283)

**Comment by skyjay1** [comment]
The log spam is because I forgot to remove a debug statement in the projectile impact event, but there is no reason for that event to fire constantly or crash…
