### ISSUE TITLE
world crashing 

### ISSUE THREAD

**Issue by Cocklet** [skyjay1/GreekFantasy#3]
[21:20:54] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.util.concurrent.CompletionException: net.minecraft.crash.ReportedException: Feature placement
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_271] {}
        at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_271] {}
Caused by: net.minecraft.crash.ReportedException: Feature placement
        at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:535) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
        at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:522) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        ... 12 more
Caused by: java.lang.NullPointerException
        at net.minecraft.tileentity.TileEntity.func_195044_w(TileEntity.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at greekfantasy.tileentity.StatueTileEntity.inventoryChanged(StatueTileEntity.java:204) ~[greekfantasy:16.3.1] {re:classloading,pl:runtimedistcleaner:A}
        at greekfantasy.tileentity.StatueTileEntity.func_174888_l(StatueTileEntity.java:220) ~[greekfantasy:16.3.1] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.inventory.IClearable.func_213131_a(SourceFile:10) ~[?:?] {re:classloading}
        at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:229) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:TemplateMixin,pl:mixin:A}
        at greekfantasy.structure.feature.SatyrCampFeature.generateTemplate(SatyrCampFeature.java:100) ~[greekfantasy:16.3.1] {re:classloading}
        at greekfantasy.structure.feature.SatyrCampFeature.generate(SatyrCampFeature.java:54) ~[greekfantasy:16.3.1] {re:classloading}
        at greekfantasy.structure.feature.SatyrCampFeature.func_241855_a(SatyrCampFeature.java:23) ~[greekfantasy:16.3.1] {re:classloading}
        at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin}
        at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_271] {}
        at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
        at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
        at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin}
        at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_271] {}
        at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
        at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
        at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin}
        at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
        at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:522) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        ... 12 more

**Comment by skyjay1** [comment]
I'll look into this. It may be an issue with Quark mixins but it could also be an error on my end.

**Comment by skyjay1** [comment]
Are you still having this issue with the latest release?

**Comment by Cocklet** [comment]
I think it’s good
