### ISSUE TITLE
Console spamming

### ISSUE THREAD

**Issue by gkchp** [skyjay1/GreekFantasy#68]
Server Version: arclight-forge-1.16-1.0.19
Forge Version: forge-1.16.5-36.1.24

console keep spamming warnings like below
```log
[10:53:00] [Worker-Main-5/WARN] [minecraft/WorldEntitySpawner]: Failed to create mob
java.lang.NullPointerException: Cannot invoke "java.util.Optional.isPresent()" because "this.treePos" is null
	at greekfantasy.entity.DryadEntity.func_213397_c(DryadEntity.java:242) ~[greekfantasy:16.4.18]
	at net.minecraft.entity.MobEntity.handler$znp001$arclight$init(MobEntityMixin.java:1566) ~[?:?]
	at net.minecraft.entity.MobEntity.<init>(MobEntityMixin.java:123) ~[?:?]
	at net.minecraft.entity.CreatureEntity.<init>(CreatureEntityMixin.java:12) ~[?:?]
	at greekfantasy.entity.DryadEntity.<init>(DryadEntity.java:83) ~[greekfantasy:16.4.18]
	at net.minecraft.entity.EntityType.func_200721_a(EntityTypeMixin.java:445) ~[?:?]
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawnerMixin.java:357) ~[?:?]
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:623) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_222602_b(ChunkStatus.java:89) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManagerMixin.java:524) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManagerMixin.java:522) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) [?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) [?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) [?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
```

**Comment by skyjay1** [comment]
There is no reason treePos should be null, it's initialized to Optional.empty(). It's possible that the arclight MobEntityMixin is doing something unexpected.
