### ISSUE TITLE
Log spam: error loading recipes

### ISSUE THREAD

**Issue by DenilsonNM** [skyjay1/GreekFantasy#97]
Minecraft version: 1.16.5
Mod loader version: 1.16.5-forge-36.2.34
Mod version: greekfantasy-16.5.5

Problem:
spams about error loading recipes for altars, apples and other items removed by the mod from what I've read

log: 
[latest.log](https://github.com/skyjay1/GreekFantasy/files/9355260/latest.log)

example:
[16:15:38] [main/ERROR]: Parsing error loading recipe greek:altar_zeus
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'rpggods:altar_shapeless'
	at net.minecraft.item.crafting.RecipeManager.func_241449_a_(RecipeManager.java:140) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager$$Lambda$7593/324477266.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:139) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) [?:?]
	at shadows.fastsuite.AuxRecipeManager.func_212853_a_(AuxRecipeManager.java:34) [?:1.1.1]
	at shadows.fastsuite.AuxRecipeManager.func_212853_a_(AuxRecipeManager.java:22) [?:1.1.1]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$5357/1756130926.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$5601/25438295.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:167) [?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1865) [?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1717) [?:?]
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1683) [?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) [?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) [?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:254) [?:?]
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:309) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$6444/506875114.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$6443/1800105174.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:111) [?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$5335/130041519.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:1000) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/9054826.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]

**Comment by skyjay1** [comment]
Greek Fantasy has a built-in data pack that is compatible with RPG Gods, but the 1.16.5 version tries to register the data pack even when RPG Gods is not installed. The mod should still load and function as intended, apologies for the spam.
Due to time constraints I no longer plan to update the 1.16.5 version to fix this.

**Comment by DenilsonNM** [comment]
I edited the file, it seems to have made the spam go away and removed everything related to rpggods, don't worry it's just for personal use
At the moment I have not presented bugs or crashes but i remove the data pack I guess, I'm a beginner I have to say
thanks for answering
